# yaml-language-server: $schema=.schema.yml
location: internal/plugin/service/organization/applicationusertoken
resource:
  refreshState: true
  description: |
    Creates and manages an application user token.
    Review the [best practices](https://aiven.io/docs/platform/concepts/application-users#security-best-practices) for securing application users and their tokens.
idAttributeComposed: [organization_id, user_id, token_prefix]
clientHandler: applicationuser
operations:
  - id: ApplicationUserAccessTokenCreate
    type: create
  - id: ApplicationUserAccessTokenDelete
    type: delete
  - id: ApplicationUserAccessTokensList
    type: read
    resultKey: tokens
    resultListLookupKeys:
      TokenPrefix: token_prefix
schema:
  full_token:
    sensitive: true
  description:
    optional: true
  extend_when_used:
    default: false
